![](https://www.dii.uchile.cl/wp-content/uploads/2021/06/Magi%CC%81ster-en-Ciencia-de-Datos.png)

# Proyecto: Innovación Tecnológica en Bodoque Bank

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### Cuerpo Docente:

- Profesor: Pablo Badilla, Ignacio Meza De La Jara
- Auxiliar: Sebastián Tinoco
- Ayudante: Diego Cortez M., Felipe Arias T.

*Por favor, lean detalladamente las instrucciones de la tarea antes de empezar a escribir.*


----

## Reglas

- Fecha de entrega: 01/06/2021
- **Grupos de 2 personas.**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Estrictamente prohibida la copia. 
- Pueden usar cualquier material del curso que estimen conveniente.

# Motivación

![](https://www.geekmi.news/__export/1621969098810/sites/debate/img/2021/05/25/juan-carlos-bodoque-1.jpg_554688468.jpg)

Juan Carlos Bodoque, el famoso periodista y empresario, decidió diversificar su portafolio de negocios y crear su propio banco. Después de varios años de investigar y analizar el mercado financiero, finalmente logró fundar su entidad bancaria con el objetivo de ofrecer a sus clientes una experiencia personalizada y confiable en sus transacciones financieras. 

Sin embargo, con las nuevas tecnologías, aparecen nuevos desafíos para la joven entidad bancaria. Por ello, Bodoque decide invertir en un equipo de expertos en tecnología y finanzas, para que Bodoque Bank implemente las últimas innovaciones en seguridad y servicio al cliente para garantizar la satisfacción y fidelización de sus clientes.

El primer objetivo de la entidad bancaria será la detección de potenciales clientes fraudulentos, para ello Bodoque Bank les hace entrega de un extenso dataset en el que se registran las actividades que han realizado sus clientes durante los últimos meses. Uno de los puntos que resaltan al pasar el conjunto de datos es que el nombre de los usuarios está protegido y que consideren cada una de las filas como una muestra independiente de la otra.

Tras la solicitud, uno de los mayores accionistas del banco llamado Mario Hugo, les sugiere que al momento de realizar el proyecto tomen las siguientes consideraciones:

- Realicen un análisis exhaustivo de cada variable, ya que los directores tienden a ser quisquillosos con puntos o definiciones sin algún fundamento claro.
- Deben ser muy claros de cómo encontrar los outliers y si es posible expliquen cómo están determinando que un cliente es fraudulento.
- Es muy probable que existan clientes con diferentes comportamientos bancarios, por lo que sería muy buena decisión de separar a los clientes en grupos etarios.


### Definición Formal del Problema

El dataset con el que se trabajará en este primer proyecto será [_The Bank Account Fraud (BAF)_](https://www.kaggle.com/datasets/sgpjesus/bank-account-fraud-dataset-neurips-2022). Este consiste en un dataset para evaluar métodos de detección de fraudes bancarios, el cuál según sus autores es:

- Realista: Se basa en un actualizado dataset de casos reales de detección de fraude bancario.
- Sesgado: Poseen distintos tipos de bias.
- Desbalanceado: Clase positiva extremadamente pequeña.
- Dinámico: Presenta datos temporales y cambios de distribución.
- Preserva la privacidad: Protege a los potenciales clientes a través de la aplicación de privacidad diferencial.

El proyecto tiene por objetivo evaluar los conocimientos adquiridos en la primera mitad del curso, consistente en manejo de datos tabulares (I/O, manipulación, agregaciones, merge y visualizaciones) más la primera parte de modelos consistente en preprocesamiento de datos y detección de anomalías. Por ende, el proyecto consiste en dos tareas principales:

1. Generar un Análisis exploratorio de Datos (EDA) que describa completamente el dataset.
2. Buscar anomalías de forma automatizada.

**Importante:** Esta permitido el uso de librerías externas a las vistas en clases para profundizar aún mas en los análisis. Sin embargo, al momento de utilizar cualqueir metodo deberán explicar que hace y el porque de su aplicación.


---

## Secciones requeridas en la entrega

La siguiente lista detalla las secciones que debe contener su notebook para resolver el proyecto. Es importante que al momento de desarrollar cada una de las secciones, estas sean escritas en un formato tipo **informe**, donde describan detalladamente cada uno de los puntos realizados.

### 1. Introducción [0.5 Puntos]

Elaborar una breve introducción con todo lo necesario para entender qué realizarán durante su proyecto. La idea es que describan de manera formal el proyecto con sus propias palabras y logren describir algunos aspectos básicos tanto del dataset como del análisis a realizar sobre los datos.

Por lo anterior, en esta sección ustedes deberán ser capaces de:

- Describir la tarea asociada al dataset.
- Describir brevemente los datos de entrada que les provee el problema.
- Plantear hipótesis de cómo podrían abordar el problema.

### 2. Lectura y Manejo de Datos [1 Punto]

Este punto tiene por objetivo evaluar la capacidad de leer y manejar distintas fuentes de datos y unirlas.
Para esto, se les provee de 3 datasets distintos: 

- `df_1.parquet` que contiene una cierta cantidad de ejemplos.
- `df_2.parquet` que contiene el resto de los ejemplos.
- `df_email_phone.parquet` que contiene características exclusivas relacionadas a los emails y teléfonos de los ejemplos.

Tanto `df_1` como `df_2` son dataframes que contienen conjuntos (no necesariamente disjuntos) de ejemplos obtenidos a partir de distintas fuentes (la primera más confiable que la segunda)  mientras que `df_email_phone` contiene nuevas características que deben ser fusionadas con el conjunto de ejemplos.
Dicho esto, para este punto se le solicita:

1. Cargar los datasets usando pandas.
2. Explorar superficialmente los datsets por medio de `.head(5)` e `.info()` y reportar número de filas y columnas de cada dataset.
3. Unir los datasets con los conjuntos de ejemplos en un único dataset.
4. Combinar el datasets con ejemplos con las nuevas características usando la estrategia `outer`.
5. Explorar nulos y duplicados de datos (i.e., generar conteos de cada uno y ver algunos de sus ejemplos), explicar su origen y entregar una solución sencilla a estos casos.
6. Limpiar datos y reportar modificaciones a los datasets originales (cuántos ejemplos se eliminaron, cuántos ejemplos quedaron finalmente, etc...).
7. Realizar una segmentación etaria de los datos creando una columna llamada `segmentacion_etaria` para clasificar a los diferentes usuarios. Para la segmentación utilice los siguientes rangos:
   - Joven (Menor a 18 años)
   - Adulto-Joven (18 - 26 años)
   - Adulto (27- 59 años)
   - Persona Mayor (60 años o mas).


### 3. Análisis Exploratorio de Datos [1 Punto]

Esta sección se busca evaluar la capacidad de generar reportes y conclusiones a partir de los patrones observados en estos.

- Utilizando `pandas-profiling` (nombre de la librería: `ydata-profiling`), explore:

    * Analizar cantidad de datos nulos, tipos de datos, duplicados, distribuciones de las variables a través de histogramas.
    * Generar visualizaciones de las interacciones (como por ejemplo, una scatter matrix) en las distintas variables.
    * Ver las correlaciones entre las distintas variables y los valores faltantes de cada una de estas. 
    * Reportar los patrones interesantes observados. Ejemplos:
        - Se observó que las variables numéricas A, B y C siguen una distribución normal / exponencial / logarítmica / no presenta distribución conocida debido a que (usar información sobre el descripción de cada variable)....
        - La mayoría de los ejemplos de las variables I, J y K tienen valor 0.
        - La variable M presenta gran cantidad de outliers.
        - Se observó que las variables categóricas E y F están bien balanceadas / presentan un gran desbalance.
        - Del gráfico de correlaciones se puede inferir que X, Y y Z tienen una correlación alta/baja entre ellas.



### 4. Preparación de Datos [1 Punto]

*Esta sección consiste en generar los distintos pasos para preparar sus datos con el fin de luego poder crear su modelo.*

Dentro de los aspectos minimos que se les solicitarán en este desarrollo estan:

- Definir preprocesadores para datos categóricos y ordinales.
- Setear las transformaciones en un `ColumnTransformer`.
- Transformar todo el datset.

**Notas**: 

- Las variables `id` y `fraud_bool` no deben ser transformadas, pero si pasadas a la siguiente etapa. (Estudiar la transformación `passthrough`).
- La salida de la transformación debe ser un pandas dataframe. Para esto, investiguen acerca de la nueva [`set_output` API](https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html). Si se levanta un error por matriz sparse, desactiven su uso en la transformación correspondiente.

### 5. Visualización en baja dimensionalidad [1 Punto]

Programar un script para proyectar los datos en baja dimensionalidad usando `PCA` o `UMAP`.

**Notas**: 

- Para realizar las proyecciones no consideren la variable `fraud_bool`, ya que esto provocaría un _data leakage_ (i.e., usar información del futuro para analizar el mismo fenómeno que quieren descubrir).
- Utilice un muestreo significativo del dataframe (10k a 25k ejemplos) para generar las proyecciones. De lo contrario, probablemente el proyector no sea capaz de asignar todos los recursos necesarios y lance alguna excepción.

Luego, por cada segmento etario generado en la sección 2, implemente un gráfico de dispersión (idealmente en plotly express) la proyección en 2D generada y coloree cada punto según la etiqueta `fraud_bool`.

Reportar si existen patrones y/o relaciones interesantes con respecto a variables de interés.


### 6. Explorar Anomalías [1.5 Puntos]

Proponer una técnica para detectar clientes fraudulentos en base a detección de anomalías. 
Al igual que el punto anterior, la técnica que proponga debe ser aplicada por separado en los diferentes segmentos etarios descritos en el punto 2 (es decir, debe entrenar un detector de anomalías para cada uno de estos grupos). 

Luego, al igual que el punto anterior, genere un gráfico de dispersión con las proyecciones 2D en donde el coloreado sea ahora las etiquetas predichas por el detector de anomalías.

Por último, usando queries de numpy/pandas, calcule dos ratios (P y R):

- P: Cantidad de ejemplos predichos correctamente como fraude / cantidad total de datos predichos como fraude.
- R: Cantidad de ejemplos predichos correctamente como fraude / cantidad total de ejemplos que eran realmente fraude.


De los resultados obtenidos responda las siguientes preguntas:

- ¿Qué significan los ratios y sus valores?
- ¿Qué tan correctas fueron las predicciones realizadas por su modelo según los ratios calculados?
- ¿Son coherentes los resultados obtenidos?.
- ¿Cómo se comportan los casos de fraudes para los diferentes rangos etarios?

Justifique cada una de sus respuestas.

---

## Esquema de la Tarea


Pueden usar el siguiente esquema para organizar la tarea (y borrar todo lo anterior).
Obviamente **no deben limitarse a lo que está escrito en esta**: puede incrementar en caso de más técnicas y obviar algunas partes en caso que alguna y otro punto no aplique a su problema.

Pueden borrar las instrucciones anteriores y quedarse solo con lo que viene a continuación.

---
<br>

<br>

<br>



# Proyecto

### Equipo:

- \<Primer integrante\>
- \<Segundo integrante\>


### Link de repositorio de GitHub: `\<http://....\>`




## 1. Introducción


In [ ]:
...

Ellipsis

## 2. Lectura y Manejo de Datos




### 2.1 Cargar datos en dataframes

In [1]:
#Conectamos el colab a drive para cargar los archivos
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#Importamos las bases de datos
import pandas as pd

df1=pd.read_parquet('/content/drive/MyDrive/lab_progra/df_1.parquet', engine='pyarrow')
df2=pd.read_parquet('/content/drive/MyDrive/lab_progra/df_2.parquet', engine='pyarrow')
df_email_phone=pd.read_parquet('/content/drive/MyDrive/lab_progra/df_email_phone.parquet', engine='pyarrow')

### 2.2 Exploración inicial

In [ ]:
print('Las dimensiones de df_1 son: '+str(df1.shape[0])+' filas por '+str(df1.shape[1])+' columnas')
print('')
print('Las dimensiones de df_2 son: '+str(df2.shape[0])+' filas por '+str(df2.shape[1])+' columnas')
print('')
print('Las dimensiones de df_email_phone son: '+str(df_email_phone.shape[0])+' filas por '+str(df_email_phone.shape[1])+' columnas')

Las dimensiones de df_1 son: 389782 filas por 29 columnas

Las dimensiones de df_2 son: 747410 filas por 29 columnas

Las dimensiones de df_email_phone son: 934730 filas por 7 columnas


In [ ]:
df1.head(5)

id  fraud_bool  income  prev_address_months_count  \
104446  729517           0     0.7                         -1   
269483  149585           0     0.8                         -1   
4102     64486           0     0.9                         -1   
351767  825283           0     0.5                         -1   
126377    8308           0     0.9                         -1   

        current_address_months_count  customer_age  days_since_request  \
104446                           305            60            0.030059   
269483                           140            50            0.015659   
4102                             171            50            0.001409   
351767                            85            30            0.027292   
126377                            39            30            0.010945   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
104446               -1.599455           AC           990  ...   
269483                3.951994           AA          1269  ...   
4102                 28.159779           AB          4430  ...   
351767               -1.310498           AB          1698  ...   
126377               -1.450972           AC           569  ...   

        proposed_credit_limit  foreign_request    source  \
104446                  500.0                0  INTERNET   
269483                  200.0                0  INTERNET   
4102                   1500.0                0  INTERNET   
351767                  200.0                0  INTERNET   
126377                  200.0                0  INTERNET   

        session_length_in_minutes device_os  keep_alive_session  \
104446                   8.865992   windows                   0   
269483                   4.654872     linux                   1   
4102                     3.720953     linux                   1   
351767                   2.912670   windows                   1   
126377                   2.283680     other                   1   

       device_fraud_count  month        x1        x2  
104446                  0      2 -0.245425  0.568811  
269483                  0      7  0.009336 -2.096682  
4102                    0      1  2.229616 -0.005823  
351767                  0      3 -0.193945  0.861207  
126377                  0      3 -2.440650  0.354986  

[5 rows x 29 columns]

In [ ]:
df2.head(5)

id  fraud_bool  income  prev_address_months_count  \
699954  303612           0     0.8                         -1   
701206  568066           0     0.9                         -1   
270304  893344           0     0.7                         -1   
346538  247688           0     0.8                         -1   
147297  674478           0     0.8                         -1   

        current_address_months_count  customer_age  days_since_request  \
699954                            21            40            0.010837   
701206                            70            50            0.711485   
270304                           133            50            0.006856   
346538                           207            50            0.026194   
147297                            24            50            0.012646   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
699954               -0.853976           AD           239  ...   
701206               25.137456           AA          1873  ...   
270304               -0.815330           AC           675  ...   
346538               -0.736615           AB           999  ...   
147297               10.744253           AA          3198  ...   

        proposed_credit_limit  foreign_request    source  \
699954                  200.0                0  INTERNET   
701206                  200.0                0  INTERNET   
270304                 1000.0                0  INTERNET   
346538                  200.0                0  INTERNET   
147297                  500.0                1  INTERNET   

        session_length_in_minutes device_os  keep_alive_session  \
699954                  48.127390     other                   0   
701206                   8.792273   windows                   1   
270304                  15.916225     other                   1   
346538                   0.509942     linux                   1   
147297                  10.562945     other                   0   

       device_fraud_count  month        x1        x2  
699954                  0      3  0.236931  0.077061  
701206                  0      3  0.571536  1.151563  
270304                  0      7  0.224252 -0.590459  
346538                  0      6  0.648528 -0.315911  
147297                  0      6  0.041475  0.383332  

[5 rows x 29 columns]

In [ ]:
df_email_phone.head(5)

id  name_email_similarity  date_of_birth_distinct_emails_4w  \
987231  624588               0.555653                                15   
79954   620810               0.849718                                 2   
567130  580633               0.110898                                 3   
500891    6379               0.671250                                15   
55399   366511               0.772932                                 7   

        email_is_free  device_distinct_emails_8w  phone_home_valid  \
987231              0                          1                 0   
79954               0                          1                 0   
567130              0                          1                 1   
500891              0                          1                 0   
55399               0                          1                 0   

        phone_mobile_valid  
987231                   1  
79954                    0  
567130                   0  
500891                   1  
55399                    1

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 389782 entries, 104446 to 193209
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   id                            389782 non-null  int64  
 1   fraud_bool                    389782 non-null  int64  
 2   income                        389782 non-null  float64
 3   prev_address_months_count     389782 non-null  int64  
 4   current_address_months_count  389782 non-null  int64  
 5   customer_age                  389782 non-null  int64  
 6   days_since_request            389782 non-null  float64
 7   intended_balcon_amount        389782 non-null  float64
 8   payment_type                  389782 non-null  object 
 9   zip_count_4w                  389782 non-null  int64  
 10  velocity_6h                   389782 non-null  float64
 11  velocity_24h                  389782 non-null  float64
 12  velocity_4w                   389782 no

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 747410 entries, 699954 to 384611
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   id                            747410 non-null  int64  
 1   fraud_bool                    747410 non-null  int64  
 2   income                        747410 non-null  float64
 3   prev_address_months_count     747410 non-null  int64  
 4   current_address_months_count  747410 non-null  int64  
 5   customer_age                  747410 non-null  int64  
 6   days_since_request            747410 non-null  float64
 7   intended_balcon_amount        747410 non-null  float64
 8   payment_type                  747410 non-null  object 
 9   zip_count_4w                  747410 non-null  int64  
 10  velocity_6h                   747410 non-null  float64
 11  velocity_24h                  747410 non-null  float64
 12  velocity_4w                   747410 no

In [ ]:
df_email_phone.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 934730 entries, 987231 to 986114
Data columns (total 7 columns):
 #   Column                            Non-Null Count   Dtype  
---  ------                            --------------   -----  
 0   id                                934730 non-null  int64  
 1   name_email_similarity             934730 non-null  float64
 2   date_of_birth_distinct_emails_4w  934730 non-null  int64  
 3   email_is_free                     934730 non-null  int64  
 4   device_distinct_emails_8w         934730 non-null  int64  
 5   phone_home_valid                  934730 non-null  int64  
 6   phone_mobile_valid                934730 non-null  int64  
dtypes: float64(1), int64(6)
memory usage: 57.1 MB


### 2.3 Unir dataframes

In [3]:
#Se agrega una columna para tener la trazabilidad de los orígenes de los datos
df1['origen']='base 1'
df2['origen']='base 2'

In [4]:
df_concat=pd.concat([df1,df2]).reset_index(drop=True)

### 2.4 Unir nuevas variables

In [5]:
bbdd_final = pd.merge(df_concat, df_email_phone, on='id', how='left')

In [ ]:
bbdd_final.shape

(1137192, 36)

### 2.5 Verificar nulos y duplicados, generar explicaciones sobre sus fuentes y proponer soluciones.



#### Nulos

Primero se cuenta la cantidad de nulos que hay por columna. Se puede observar que las columnas que se agregaron por el cruce son las que tienen estos valores nulos. 

In [ ]:
bbdd_final.isnull().sum()

id                                      0
fraud_bool                              0
income                                  0
prev_address_months_count               0
current_address_months_count            0
customer_age                            0
days_since_request                      0
intended_balcon_amount                  0
payment_type                            0
zip_count_4w                            0
velocity_6h                             0
velocity_24h                            0
velocity_4w                             0
bank_branch_count_8w                    0
employment_status                       0
credit_risk_score                       0
housing_status                          0
bank_months_count                       0
has_other_cards                         0
proposed_credit_limit                   0
foreign_request                         0
source                                  0
session_length_in_minutes               0
device_os                         

Por la cantidad repetida de nulos en cada columna, una hipótesis es que todos esos valores nulos provienen de los mismos registros. Esto se comprueba a continuación, donde primero se toma una columna cualquiera, luego se filtra por las filas nulas y se vuelve a calcular la cantidad de nulos que hay por cada columna. Si da la misma cantidad, esto significa que los nulos provienen de los mismos registros.

In [10]:
nulos=bbdd_final[bbdd_final['name_email_similarity'].isnull()]

In [11]:
nulos.isnull().sum()

id                                      0
fraud_bool                              0
income                                  0
prev_address_months_count               0
current_address_months_count            0
customer_age                            0
days_since_request                      0
intended_balcon_amount                  0
payment_type                            0
zip_count_4w                            0
velocity_6h                             0
velocity_24h                            0
velocity_4w                             0
bank_branch_count_8w                    0
employment_status                       0
credit_risk_score                       0
housing_status                          0
bank_months_count                       0
has_other_cards                         0
proposed_credit_limit                   0
foreign_request                         0
source                                  0
session_length_in_minutes               0
device_os                         

Como dio la misma cantidad de nulos que en la base donde no se filtro, quiere decir que todos los nulos provienen de los mismos registros.

Para saber la razón de los nulos, se separá la base en una que contiene sólo los registros con nulos y la otra en una base que sólo contenga datos sin nulos, luego de esta separación se verificarán 2 cosas. Primero, ver si hay diferencias notables en los estadísticos de ambas bases. Esto con el objetivo de ver si hay alguna diferencia en las poblaciones de ambas bases que pueda llevar a pensar que hay una variable que se correlaciona con la nulidad de algunos datos.

Lo segundo que se verificará es si el origen de los datos puede llegar a afectar la nulidad, debido a que df1 y df2 tienen 2 orígenes distintos y además, los datos de df2 no son tan confiables, según enunciado, pero no sabemos el por qué.

##### Estadísticos

Ya habíamos separado una base solo con nulos, así que falta armar la base sin nulos. Luego de crearla, se verán las diferencias entre los estadísticos de ambas bases.

In [6]:
sin_nulos=bbdd_final[bbdd_final['name_email_similarity'].notnull()]

In [7]:
sin_nulos.describe().transpose()

count           mean            std  \
id                                1057465.0  500141.823877  288698.160011   
fraud_bool                        1057465.0       0.011076       0.104660   
income                            1057465.0       0.578704       0.288263   
prev_address_months_count         1057465.0      14.648055      42.987418   
current_address_months_count      1057465.0      99.171658      94.032858   
customer_age                      1057465.0      41.342626      13.764593   
days_since_request                1057465.0       0.901141       4.994621   
intended_balcon_amount            1057465.0       8.563240      20.533975   
zip_count_4w                      1057465.0    1518.330710     966.003968   
velocity_6h                       1057465.0    5492.639968    2939.143965   
velocity_24h                      1057465.0    4661.051132    1450.642353   
velocity_4w                       1057465.0    4734.927085     871.015792   
bank_branch_count_8w              1057465.0     200.955029     473.432868   
credit_risk_score                 1057465.0     139.279955      71.445968   
bank_months_count                 1057465.0      11.147778      12.127487   
has_other_cards                   1057465.0       0.249702       0.432841   
proposed_credit_limit             1057465.0     551.541668     506.698808   
foreign_request                   1057465.0       0.023902       0.152742   
session_length_in_minutes         1057465.0       7.816282       8.241738   
keep_alive_session                1057465.0       0.556186       0.496833   
device_fraud_count                1057465.0       0.000000       0.000000   
month                             1057465.0       3.656299       2.117072   
x1                                1057465.0       0.014140       1.013339   
x2                                1057465.0       0.011147       1.012887   
name_email_similarity             1057465.0       0.487641       0.291457   
date_of_birth_distinct_emails_4w  1057465.0       7.778368       4.814321   
email_is_free                     1057465.0       0.518114       0.499672   
device_distinct_emails_8w         1057465.0       1.022282       0.191573   
phone_home_valid                  1057465.0       0.493414       0.499957   
phone_mobile_valid                1057465.0       0.856897       0.350178   

                                           min            25%            50%  \
id                                0.000000e+00  249877.000000  500452.000000   
fraud_bool                        0.000000e+00       0.000000       0.000000   
income                            1.000000e-01       0.300000       0.600000   
prev_address_months_count        -1.000000e+00      -1.000000      -1.000000   
current_address_months_count     -1.000000e+00      27.000000      64.000000   
customer_age                      1.000000e+01      30.000000      50.000000   
days_since_request                3.112791e-08       0.007444       0.015666   
intended_balcon_amount           -1.553733e+01      -1.179802      -0.833980   
zip_count_4w                      1.000000e+00     886.000000    1208.000000   
velocity_6h                      -1.741097e+02    3339.402765    5193.504274   
velocity_24h                      1.322325e+03    3504.200445    4639.960378   
velocity_4w                       2.870592e+03    4238.832450    4813.957271   
bank_branch_count_8w              0.000000e+00       1.000000      10.000000   
credit_risk_score                -1.770000e+02      90.000000     130.000000   
bank_months_count                -1.000000e+00       1.000000       6.000000   
has_other_cards                   0.000000e+00       0.000000       0.000000   
proposed_credit_limit             1.900000e+02     200.000000     200.000000   
foreign_request                   0.000000e+00       0.000000       0.000000   
session_length_in_minutes        -1.000000e+00       3.150868       5.248331   
keep_alive_session                0.000000e+00    

In [12]:
nulos.describe().transpose()

count           mean            std  \
id                                79727.0  499734.521003  289045.533576   
fraud_bool                        79727.0       0.010122       0.100099   
income                            79727.0       0.576482       0.287923   
prev_address_months_count         79727.0      14.633010      42.898773   
current_address_months_count      79727.0      99.221293      94.473318   
customer_age                      79727.0      41.359765      13.791121   
days_since_request                79727.0       0.909396       5.078683   
intended_balcon_amount            79727.0       8.531122      20.514493   
zip_count_4w                      79727.0    1521.203432     968.044676   
velocity_6h                       79727.0    5480.778022    2951.912548   
velocity_24h                      79727.0    4669.852812    1459.354979   
velocity_4w                       79727.0    4732.058053     874.643868   
bank_branch_count_8w              79727.0     205.464046     478.814725   
credit_risk_score                 79727.0     139.048302      71.538052   
bank_months_count                 79727.0      11.158416      12.139104   
has_other_cards                   79727.0       0.248912       0.432385   
proposed_credit_limit             79727.0     552.586075     505.127016   
foreign_request                   79727.0       0.023593       0.151778   
session_length_in_minutes         79727.0       7.835369       8.252677   
keep_alive_session                79727.0       0.557013       0.496742   
device_fraud_count                79727.0       0.000000       0.000000   
month                             79727.0       3.655098       2.114583   
x1                                79727.0       0.020506       1.010037   
x2                                79727.0       0.009233       1.012735   
name_email_similarity                 0.0            NaN            NaN   
date_of_birth_distinct_emails_4w      0.0            NaN            NaN   
email_is_free                         0.0            NaN            NaN   
device_distinct_emails_8w             0.0            NaN            NaN   
phone_home_valid                      0.0            NaN            NaN   
phone_mobile_valid                    0.0            NaN            NaN   

                                           min            25%            50%  \
id                                3.700000e+01  250654.500000  498688.000000   
fraud_bool                        0.000000e+00       0.000000       0.000000   
income                            1.000000e-01       0.300000       0.600000   
prev_address_months_count        -1.000000e+00      -1.000000      -1.000000   
current_address_months_count     -1.000000e+00      26.000000      64.000000   
customer_age                      1.000000e+01      30.000000      50.000000   
days_since_request                3.839882e-07       0.007316       0.015572   
intended_balcon_amount           -1.240574e+01      -1.182137      -0.836201   
zip_count_4w                      4.000000e+00     886.000000    1212.000000   
velocity_6h                       1.727520e+01    3304.988517    5175.170149   
velocity_24h                      1.328306e+03    3501.726907    4657.212140   
velocity_4w                       2.961316e+03    4239.241432    4810.641928   
bank_branch_count_8w              0.000000e+00       1.000000      10.000000   
credit_risk_score                -1.480000e+02      89.000000     129.000000   
bank_months_count                -1.000000e+00       1.000000       6.000000   
has_other_cards                   0.000000e+00       0.000000       0.000000   
proposed_credit_limit             1.900000e+02     200.000000     200.000000   
foreign_request                   0.000000e+00       0.000000       0.000000   
session_length_in_minutes        -1.000000e+00       3.177801       5.255102   
keep_alive_session                0.000000e+00       0.000000       1.000000   
device_fraud_count            

In [13]:
resta1=sin_nulos.describe().transpose()

In [ ]:
resta2=nulos.describe().transpose()

In [ ]:
resta1-resta2

count        mean         std  \
id                                 977738.0  407.302874 -347.373566   
fraud_bool                         977738.0    0.000954    0.004562   
income                             977738.0    0.002221    0.000340   
prev_address_months_count          977738.0    0.015044    0.088645   
current_address_months_count       977738.0   -0.049635   -0.440460   
customer_age                       977738.0   -0.017139   -0.026528   
days_since_request                 977738.0   -0.008255   -0.084062   
intended_balcon_amount             977738.0    0.032118    0.019482   
zip_count_4w                       977738.0   -2.872722   -2.040708   
velocity_6h                        977738.0   11.861946  -12.768583   
velocity_24h                       977738.0   -8.801680   -8.712626   
velocity_4w                        977738.0    2.869032   -3.628076   
bank_branch_count_8w               977738.0   -4.509017   -5.381857   
credit_risk_score                  977738.0    0.231653   -0.092084   
bank_months_count                  977738.0   -0.010638   -0.011617   
has_other_cards                    977738.0    0.000790    0.000455   
proposed_credit_limit              977738.0   -1.044407    1.571792   
foreign_request                    977738.0    0.000308    0.000964   
session_length_in_minutes          977738.0   -0.019087   -0.010939   
keep_alive_session                 977738.0   -0.000828    0.000091   
device_fraud_count                 977738.0    0.000000    0.000000   
month                              977738.0    0.001201    0.002488   
x1                                 977738.0   -0.006366    0.003302   
x2                                 977738.0    0.001913    0.000152   
name_email_similarity             1057465.0         NaN         NaN   
date_of_birth_distinct_emails_4w  1057465.0         NaN         NaN   
email_is_free                     1057465.0         NaN         NaN   
device_distinct_emails_8w         1057465.0         NaN         NaN   
phone_home_valid                  1057465.0         NaN         NaN   
phone_mobile_valid                1057465.0         NaN         NaN   

                                           min         25%          50%  \
id                               -3.700000e+01 -777.500000  1764.000000   
fraud_bool                        0.000000e+00    0.000000     0.000000   
income                            0.000000e+00    0.000000     0.000000   
prev_address_months_count         0.000000e+00    0.000000     0.000000   
current_address_months_count      0.000000e+00    1.000000     0.000000   
customer_age                      0.000000e+00    0.000000     0.000000   
days_since_request               -3.528603e-07    0.000128     0.000094   
intended_balcon_amount           -3.131593e+00    0.002336     0.002221   
zip_count_4w                     -3.000000e+00    0.000000    -4.000000   
velocity_6h                      -1.913849e+02   34.414248    18.334124   
velocity_24h                     -5.980949e+00    2.473538   -17.251762   
velocity_4w                      -9.072466e+01   -0.408982     3.315343   
bank_branch_count_8w              0.000000e+00    0.000000     0.000000   
credit_risk_score                -2.900000e+01    1.000000     1.000000   
bank_months_count                 0.000000e+00    0.000000     0.000000   
has_other_cards                   0.000000e+00    0.000000     0.000000   
proposed_credit_limit             0.000000e+00    0.000000     0.000000   
foreign_request                   0.000000e+00    0.000000     0.000000   
session_length_in_minutes         0.000000e+00   -0.026933    -0.006771   
keep_alive_session                0.000000e+00    0.000000     0.000000   
device_fraud_count                0.000000e+00    0.000000     0.000000   
month                             0.000000e+00    0.000000     0.000000   
x1                               -5.774191e-01   -0.013670    -0.009219   
x2                               -3.

Al ver las diferencias que pueden haber entre los estadísticos de ambas bases, se puede ver que las mayores diferencias se dan en las columnas: zip_count_4w, velocity_6h, velocity_24h, velocity_4w y bank_branch_count_8w. Al observar los valores de esas columnas en los estadísticos de las bases respectivas, se puede observar que la magnitud más alta en comparación a las otras columnas se debe al rango en donde se mueven esas variables, siendo estos mucho más amplios que el resto de las variables. **test de diferencia de medias** **lo puedo aplicar falta ver si las variables categóricas afectan en algo, se me ocurre ver el conteo por base de cada una **

Por lo que se concluye que no hay diferencias significativas entre ambos estadisticos. Por lo que se explorará si el origen de los nulos proviene de los orígenes de las bases.

##### Origen

In [14]:
nulos.groupby(['origen'])['origen'].count()

origen
base 2    79727
Name: origen, dtype: int64

In [15]:
sin_nulos.groupby(['origen'])['origen'].count()

origen
base 1    389782
base 2    667683
Name: origen, dtype: int64

Se puede observar que los datos nulos provienen solo del origen de la base 2. Esto se puede deber a la confiabilidad de los datos que se informa en el inicio del proyecto, donde mencionan la confiabilidad de ambas bases: *"la primera más confiable que la segunda"*. No mencionan más sobre la confiabilidad de los datos, pero con la información que tenemos se puede suponer que la confiabilidad de los datos de la segunda base puede tener relación a que en ella no se pudieron recolectar datos de contacto del cliente por un motivo aleatorio, esto debido a que no se observó que alguna variable extra del dataset tuviera relación con la nulidad de los datos.

Como este tipo de nulo es un missing at random, la solución más óptima es dropear los registros que contengan los nulos.

#### Duplicados


Primero se verá cuántos datos son los duplicados en la base y luego, se filtrará la base por los datos que se repiten más de una vez con el objetivo de ver ejemplos de estps casos.

In [16]:
len(bbdd_final)-len(bbdd_final.drop_duplicates())

163292

In [17]:
base_duplicados=bbdd_final.groupby(['id',
 'fraud_bool',
 'income',
 'prev_address_months_count',
 'current_address_months_count',
 'customer_age',
 'days_since_request',
 'intended_balcon_amount',
 'payment_type',
 'zip_count_4w',
 'velocity_6h',
 'velocity_24h',
 'velocity_4w',
 'bank_branch_count_8w',
 'employment_status',
 'credit_risk_score',
 'housing_status',
 'bank_months_count',
 'has_other_cards',
 'proposed_credit_limit',
 'foreign_request',
 'source',
 'session_length_in_minutes',
 'device_os',
 'keep_alive_session',
 'device_fraud_count',
 'month',
 'x1',
 'x2',
 'name_email_similarity',
 'date_of_birth_distinct_emails_4w',
 'email_is_free',
 'device_distinct_emails_8w',
 'phone_home_valid',
 'phone_mobile_valid'],as_index=False).size()

In [18]:
base_duplicados=base_duplicados[base_duplicados['size']>1]

In [19]:
base_duplicados

id  fraud_bool  income  prev_address_months_count  \
8           10           0     0.7                         -1   
12          14           0     0.9                         -1   
17          19           0     0.5                         -1   
35          39           0     0.1                         -1   
49          55           0     0.6                         -1   
...        ...         ...     ...                        ...   
873677  999899           0     0.7                         -1   
873679  999901           0     0.4                         -1   
873688  999911           1     0.8                         -1   
873735  999962           0     0.2                         -1   
873767  999996           0     0.9                         38   

        current_address_months_count  customer_age  days_since_request  \
8                                269            50            0.017052   
12                                38            40            0.011142   
17                                18            50            0.006434   
35                               189            30            0.001039   
49                               216            60            0.022977   
...                              ...           ...                 ...   
873677                           112            50            0.006232   
873679                           160            40            0.027443   
873688                            50            50            0.002217   
873735                            14            20            0.021409   
873767                             8            20            0.009012   

        intended_balcon_amount payment_type  zip_count_4w  ...  month  \
8                    18.113431           AA          1008  ...      7   
12                   -0.700248           AB           999  ...      1   
17                   -1.351873           AB           705  ...      7   
35                   -0.576867           AB          1644  ...      3   
49                   -0.601287           AB          1126  ...      7   
...                        ...          ...           ...  ...    ...   
873677               -0.665022           AB           937  ...      3   
873679               -0.749521           AB          1140  ...      6   
873688               -0.830081           AC           558  ...      4   
873735               -1.502281           AC           692  ...      6   
873767               50.289551           AA          1728  ...      6   

              x1        x2  name_email_similarity  \
8       0.819086  0.995956               0.409915   
12     -1.204976 -0.460171               0.925234   
17      1.017089 -0.557888               0.401173   
35      1.620199  0.132025               0.868037   
49      1.643214  1.155003               0.387457   
...          ...       ...                    ...   
873677 -0.880549 -0.438311               0.780176   
873679 -0.805069  0.074894               0.910497   
873688  1.479974 -0.398567               0.997162   
873735  0.193208  0.839659               0.249010   
873767  0.802064 -1.299359               0.475857   

       date_of_birth_distinct_emails_4w  email_is_free  \
8                                   5.0            0.0   
12                                  9.0            1.0   
17                                 13.0            0.0   
35                                  8.0            1.0   
49                                  3.0            0.0   
...                                 ...            ...   
873677                              8.0            1.0   
873679                              9.0            1.0   
873688                              4.0            1.0   
873735                             11.0            1.0   
873767                             12.0            1.0   

       device_distinct_emails_8w  phone_home_valid  phone_mobile_valid  size  
8                            1.0               1.0  

Como cada registro representa la situación de un cliente específico, que hayan registros con la misma información es incorrecto y podría inducir a sesgos en el análisis, por lo que la forma de solucionar este problema es dropeando los registros duplicados.

### 2.6 Limpiar

Se eliminan de la base los registros de la forma mencionada en la sección anterior

In [20]:
bbdd_final=bbdd_final.drop_duplicates()

In [21]:
bbdd_final=bbdd_final[bbdd_final['name_email_similarity'].notnull()]

Además de eliminar esos datos, se eliminan las columnas x1 y x2, ya que no significan nada dentro de la base de datos.

In [22]:
bbdd_final=bbdd_final.drop(['x1','x2'], axis=1)

### 2.7 Nueva columna con segmentaciones

In [23]:
import numpy as np
bins = [0, 18, 26, 59, np.inf]
names = ['Menor a 18', '19 - 26 años', '27 - 59 años', '60 años o mas']

bbdd_final['segmentacion_etaria'] = pd.cut(bbdd_final['customer_age'], bins, labels=names)

## 3. Análisis Exploratorio de Datos

In [ ]:
!pip install ydata_profiling

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.3/352.3 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 12.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 kB 32.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 31.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.4/455.4 kB 41.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 63.9 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=40699c92fb96b5180de7e3f396097a0b4496b40e475400b053a35e5aeab5620a
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
  Attempting uninstall: wordcloud
    Found existing installation: wordcloud 1.8.2.2
    

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(bbdd_final, title="EDA")
# profile.to_file("eda.html")

### 3.1 Análisis del EDA

EDAAA


## 4. Preprocesamiento

### 4.1 Declarar `ColumnTransformer`

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler, PowerTransformer

In [25]:
bbdd_final.columns

Index(['id', 'fraud_bool', 'income', 'prev_address_months_count',
       'current_address_months_count', 'customer_age', 'days_since_request',
       'intended_balcon_amount', 'payment_type', 'zip_count_4w', 'velocity_6h',
       'velocity_24h', 'velocity_4w', 'bank_branch_count_8w',
       'employment_status', 'credit_risk_score', 'housing_status',
       'bank_months_count', 'has_other_cards', 'proposed_credit_limit',
       'foreign_request', 'source', 'session_length_in_minutes', 'device_os',
       'keep_alive_session', 'device_fraud_count', 'month', 'origen',
       'name_email_similarity', 'date_of_birth_distinct_emails_4w',
       'email_is_free', 'device_distinct_emails_8w', 'phone_home_valid',
       'phone_mobile_valid', 'segmentacion_etaria'],
      dtype='object')

In [26]:
variables_numericas=[
    'income',
    'prev_address_months_count',
    'current_address_months_count',
    'customer_age',
    'days_since_request',
    'intended_balcon_amount',
    'zip_count_4w',
    'velocity_6h',
    'velocity_24h',
    'velocity_4w',
    'bank_branch_count_8w',
    'credit_risk_score',
    'bank_months_count',
    'proposed_credit_limit',
    'session_length_in_minutes',
    'month',
    'name_email_similarity',
    'date_of_birth_distinct_emails_4w'
]
variables_ordinales=[
    'payment_type',
    'employment_status',
    'housing_status',
    'has_other_cards',
    'foreign_request',
    'source',
    'device_os',
    'keep_alive_session',
    'device_fraud_count',
    'origen',
    'email_is_free',
    'device_distinct_emails_8w',
    'phone_home_valid',
    'phone_mobile_valid',
    'segmentacion_etaria'
] 

In [27]:
#Realizamos One Hot Encoder a las variablees ordinales
column_transformer = make_column_transformer(
    ('passthrough', ['id', 'fraud_bool']),
    (StandardScaler(), variables_numericas),
    (OneHotEncoder(), variables_ordinales),
)

In [28]:
bbdd_final.columns

Index(['id', 'fraud_bool', 'income', 'prev_address_months_count',
       'current_address_months_count', 'customer_age', 'days_since_request',
       'intended_balcon_amount', 'payment_type', 'zip_count_4w', 'velocity_6h',
       'velocity_24h', 'velocity_4w', 'bank_branch_count_8w',
       'employment_status', 'credit_risk_score', 'housing_status',
       'bank_months_count', 'has_other_cards', 'proposed_credit_limit',
       'foreign_request', 'source', 'session_length_in_minutes', 'device_os',
       'keep_alive_session', 'device_fraud_count', 'month', 'origen',
       'name_email_similarity', 'date_of_birth_distinct_emails_4w',
       'email_is_free', 'device_distinct_emails_8w', 'phone_home_valid',
       'phone_mobile_valid', 'segmentacion_etaria'],
      dtype='object')

### 4.2 Transformar datos

In [29]:
transformed_data = column_transformer.fit_transform(bbdd_final)

In [30]:
new_columns = column_transformer.named_transformers_['onehotencoder'].get_feature_names_out(variables_ordinales)
all_columns = list(new_columns) + list(bbdd_final.columns.drop(variables_ordinales))

df_encoded = pd.DataFrame(transformed_data, columns=all_columns)

In [31]:
df_encoded.columns.values

array(['payment_type_AA', 'payment_type_AB', 'payment_type_AC',
       'payment_type_AD', 'payment_type_AE', 'employment_status_CA',
       'employment_status_CB', 'employment_status_CC',
       'employment_status_CD', 'employment_status_CE',
       'employment_status_CF', 'employment_status_CG',
       'housing_status_BA', 'housing_status_BB', 'housing_status_BC',
       'housing_status_BD', 'housing_status_BE', 'housing_status_BF',
       'housing_status_BG', 'has_other_cards_0', 'has_other_cards_1',
       'foreign_request_0', 'foreign_request_1', 'source_INTERNET',
       'source_TELEAPP', 'device_os_linux', 'device_os_macintosh',
       'device_os_other', 'device_os_windows', 'device_os_x11',
       'keep_alive_session_0', 'keep_alive_session_1',
       'device_fraud_count_0', 'origen_base 1', 'origen_base 2',
       'email_is_free_0.0', 'email_is_free_1.0',
       'device_distinct_emails_8w_-1.0', 'device_distinct_emails_8w_0.0',
       'device_distinct_emails_8w_1.0', 'device_di

## 5. Visualización en Baja Dimensionalidad

### 5.1 Muestrear dataframe

In [32]:
from sklearn.decomposition import PCA

In [33]:
muestreo = df_encoded.sample(n=10000, replace=True, random_state=190423)
caract = df_encoded.columns.drop('fraud_bool')

pca = PCA(n_components=2)
transformed_data = pca.fit_transform(muestreo[caract])

In [34]:
transformed_data.shape

(10000, 2)

In [35]:
muestreo['comp1'] = transformed_data[:,0]
muestreo['comp2'] = transformed_data[:,1]

In [36]:
clases=['segmentacion_etaria_19 - 26 años',
       'segmentacion_etaria_27 - 59 años', 'segmentacion_etaria_60 años o mas',
       'segmentacion_etaria_Menor a 18']

### 5.2 Proyectar y agregar proyecciones al dataframe de muestreo

**ACÁ HAY UN PROBLEMA, SI SE HACE LA SUMA DE LAS 4 BASES, NO SUMAN 10000**


In [37]:
menor = muestreo[muestreo['segmentacion_etaria_Menor a 18']>0][['comp1','comp2', 'fraud_bool']]
joven = muestreo[muestreo['segmentacion_etaria_19 - 26 años']>0][['comp1','comp2', 'fraud_bool']]
adulto = muestreo[muestreo['segmentacion_etaria_27 - 59 años']>0][['comp1','comp2', 'fraud_bool']]
mayor = muestreo[muestreo['segmentacion_etaria_60 años o mas']>0][['comp1','comp2', 'fraud_bool']]

### 5.3 Visualizar según rangos etarios

In [93]:
import plotly.express as px

fig = px.scatter(menor, x='comp1', y='comp2', color='fraud_bool')
fig.show()

In [ ]:
fig = px.scatter(joven, x='comp1', y='comp2', color='fraud_bool')
fig.show()

In [ ]:
fig = px.scatter(adulto, x='comp1', y='comp2', color='fraud_bool')
fig.show()

In [ ]:
fig = px.scatter(mayor, x='comp1', y='comp2', color='fraud_bool')
fig.show()

## 6. Anomalías

### 6.1 Implementar detector de anomalías sobre dataframe de muestreo

La forma en que se detectaran anomalías por rango etario serán usando modelos de clasificación. Se probarán base dummy,decisiontree y knn. Los modelos que presenten un mejor F1-Score serán los elegidos. 

In [38]:
from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [82]:
from sklearn.metrics import f1_score, recall_score, precision_score
from sklearn.model_selection import train_test_split
import numpy as np

def run_classifier(clf, X, y):
        metrics = {'f1-score': [], 'precision': [], 'recall': []}
    
        #dividiendo los datos de entrenamiento y validación
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30,  random_state=101)

        clf.fit(X_train,y_train) #fiteamos el modelo
        predictions = clf.predict(X_test) #Generamos las predicciones
       
        
        ### FIN COMPLETAR ACÁ
        
        metrics['y_pred'] = predictions
        metrics['f1-score'].append(f1_score(y_test, predictions)) 
        metrics['recall'].append(recall_score(y_test, predictions))
        metrics['precision'].append(precision_score(y_test, predictions))
        matriz= confusion_matrix(y_test, predictions)


        return metrics, matriz

#### Menor

In [83]:
X=menor[['comp1','comp2']]
y=menor['fraud_bool']

c0 = ("Base Dummy", DummyClassifier(strategy='stratified', random_state=10))
c1 = ("Decision Tree", DecisionTreeClassifier(max_depth=5))
c2 = ("KNN", KNeighborsClassifier(n_neighbors=10))

classifiers = [c0, c1, c2]

results = {}
for name, clf in classifiers:
    metrics, matriz = run_classifier(clf, X, y)   # hay que implementarla en el bloque anterior.
    results[name] = metrics
    print("----------------")
    print("Resultados para clasificador: ", name) 
    print(matriz)
    print("Precision promedio:", np.array(metrics['precision']).mean())
    print("Recall promedio:", np.array(metrics['recall']).mean())
    print("F1-score promedio:", np.array(metrics['f1-score']).mean())
    print("----------------\n\n")  

----------------
Resultados para clasificador:  Base Dummy
[[279 239]
 [208 198]]
Precision promedio: 0.45308924485125857
Recall promedio: 0.4876847290640394
F1-score promedio: 0.4697508896797153
----------------


----------------
Resultados para clasificador:  Decision Tree
[[511   7]
 [404   2]]
Precision promedio: 0.2222222222222222
Recall promedio: 0.0049261083743842365
F1-score promedio: 0.00963855421686747
----------------


----------------
Resultados para clasificador:  KNN
[[350 168]
 [290 116]]
Precision promedio: 0.4084507042253521
Recall promedio: 0.2857142857142857
F1-score promedio: 0.336231884057971
----------------




Acá se elige el modelo de base dummy

In [127]:
X=menor[['comp1','comp2']]
y=menor['fraud_bool']

X_train_menor, X_test_menor, y_train_menor, y_test_menor = train_test_split(X, y, test_size=.30,  random_state=101)
clf_menor=DummyClassifier(strategy='stratified', random_state=10)
clf_menor.fit(X_train_menor,y_train_menor) #fiteamos el modelo
predictions_menor = clf_menor.predict(X_test_menor) #Generamos las predicciones
predictions_menor_s=pd.DataFrame(predictions_menor).reset_index()
menor_2 =  pd.concat([X_test_menor.reset_index(), predictions_menor_s], axis=1)
confusion_matrix(y_test_menor, predictions_menor)

array([[279, 239],
       [208, 198]])

#### Joven

In [56]:
# Ejecutar este código

X=joven[['comp1','comp2']]
y=joven['fraud_bool']

c0 = ("Base Dummy", DummyClassifier(strategy='stratified', random_state=10))
c1 = ("Decision Tree", DecisionTreeClassifier(max_depth=5))
c2 = ("KNN", KNeighborsClassifier(n_neighbors=10))

classifiers = [c0, c1, c2]

results = {}
for name, clf in classifiers:
    metrics, matriz = run_classifier(clf, X, y)   # hay que implementarla en el bloque anterior.
    results[name] = metrics
    print("----------------")
    print("Resultados para clasificador: ", name) 
    print(matriz)
    print("Precision promedio:", np.array(metrics['precision']).mean())
    print("Recall promedio:", np.array(metrics['recall']).mean())
    print("F1-score promedio:", np.array(metrics['f1-score']).mean())
    print("----------------\n\n")  

----------------
Resultados para clasificador:  Base Dummy
[[341 244]
 [238 182]]
Precision promedio: 0.4272300469483568
Recall promedio: 0.43333333333333335
F1-score promedio: 0.43026004728132394
----------------


----------------
Resultados para clasificador:  Decision Tree
[[571  14]
 [409  11]]
Precision promedio: 0.44
Recall promedio: 0.02619047619047619
F1-score promedio: 0.04943820224719101
----------------


----------------
Resultados para clasificador:  KNN
[[454 131]
 [334  86]]
Precision promedio: 0.39631336405529954
Recall promedio: 0.20476190476190476
F1-score promedio: 0.27001569858712715
----------------




Acá se elige el modelo de base dummy

In [129]:
X=joven[['comp1','comp2']]
y=joven['fraud_bool']

X_train_joven, X_test_joven, y_train_joven, y_test_joven = train_test_split(X, y, test_size=.30,  random_state=101)
clf_joven=DummyClassifier(strategy='stratified', random_state=10)
clf_joven.fit(X_train_joven,y_train_joven) #fiteamos el modelo
predictions_joven = clf_joven.predict(X_test_joven) #Generamos las predicciones
predictions_joven_s=pd.DataFrame(predictions_joven).reset_index()
joven_2 =  pd.concat([X_test_joven.reset_index(), predictions_joven_s], axis=1)
confusion_matrix(y_test_joven, predictions_joven)

array([[341, 244],
       [238, 182]])

#### Adulto

In [57]:
# Ejecutar este código

X=adulto[['comp1','comp2']]
y=adulto['fraud_bool']

c0 = ("Base Dummy", DummyClassifier(strategy='stratified',  random_state=10))
c1 = ("Decision Tree", DecisionTreeClassifier(max_depth=5))
c3 = ("KNN", KNeighborsClassifier(n_neighbors=10))


classifiers = [c0, c1, c2]

results = {}
for name, clf in classifiers:
    metrics, matriz = run_classifier(clf, X, y)   # hay que implementarla en el bloque anterior.
    results[name] = metrics
    print("----------------")
    print("Resultados para clasificador: ", name) 
    print(matriz)
    print("Precision promedio:", np.array(metrics['precision']).mean())
    print("Recall promedio:", np.array(metrics['recall']).mean())
    print("F1-score promedio:", np.array(metrics['f1-score']).mean())
    print("----------------\n\n")  

----------------
Resultados para clasificador:  Base Dummy
[[29 41]
 [35 46]]
Precision promedio: 0.5287356321839081
Recall promedio: 0.5679012345679012
F1-score promedio: 0.5476190476190477
----------------


----------------
Resultados para clasificador:  Decision Tree
[[26 44]
 [39 42]]
Precision promedio: 0.4883720930232558
Recall promedio: 0.5185185185185185
F1-score promedio: 0.5029940119760479
----------------


----------------
Resultados para clasificador:  KNN
[[40 30]
 [44 37]]
Precision promedio: 0.5522388059701493
Recall promedio: 0.4567901234567901
F1-score promedio: 0.5
----------------




Acá se elige el modelo de base dummy

In [130]:
X=adulto[['comp1','comp2']]
y=adulto['fraud_bool']

X_train_adulto, X_test_adulto, y_train_adulto, y_test_adulto = train_test_split(X, y, test_size=.30,  random_state=101)
clf_adulto=DummyClassifier(strategy='stratified', random_state=10)
clf_adulto.fit(X_train_adulto,y_train_adulto) #fiteamos el modelo
predictions_adulto = clf_adulto.predict(X_test_adulto) #Generamos las predicciones
predictions_adulto_s=pd.DataFrame(predictions_adulto).reset_index()
adulto_2 =  pd.concat([X_test_adulto.reset_index(), predictions_adulto_s], axis=1)
confusion_matrix(y_test_adulto, predictions_adulto)

array([[29, 41],
       [35, 46]])

#### Mayor

In [58]:
# Ejecutar este código

X=mayor[['comp1','comp2']]
y=mayor['fraud_bool']

c0 = ("Base Dummy", DummyClassifier(strategy='stratified',  random_state=10))
c1 = ("Decision Tree", DecisionTreeClassifier(max_depth=5))
c2 = ("KNN", KNeighborsClassifier(n_neighbors=10))


classifiers = [c0, c1, c2]

results = {}
for name, clf in classifiers:
    metrics, matriz = run_classifier(clf, X, y)   # hay que implementarla en el bloque anterior.
    results[name] = metrics
    print("----------------")
    print("Resultados para clasificador: ", name) 
    print(matriz)
    print("Precision promedio:", np.array(metrics['precision']).mean())
    print("Recall promedio:", np.array(metrics['recall']).mean())
    print("F1-score promedio:", np.array(metrics['f1-score']).mean())
    print("----------------\n\n")  

----------------
Resultados para clasificador:  Base Dummy
[[325 219]
 [210 148]]
Precision promedio: 0.4032697547683924
Recall promedio: 0.4134078212290503
F1-score promedio: 0.4082758620689655
----------------


----------------
Resultados para clasificador:  Decision Tree
[[457  87]
 [307  51]]
Precision promedio: 0.3695652173913043
Recall promedio: 0.1424581005586592
F1-score promedio: 0.20564516129032254
----------------


----------------
Resultados para clasificador:  KNN
[[454  90]
 [294  64]]
Precision promedio: 0.4155844155844156
Recall promedio: 0.1787709497206704
F1-score promedio: 0.25
----------------




Acá se elige el modelo de base dummy en cada segmentación debido a que es el modelo que entrega los mejores F1-Score.

In [131]:
X=mayor[['comp1','comp2']]
y=mayor['fraud_bool']

X_train_mayor, X_test_mayor, y_train_mayor, y_test_mayor = train_test_split(X, y, test_size=.30,  random_state=101)
clf_mayor=DummyClassifier(strategy='stratified', random_state=10)
clf_mayor.fit(X_train_mayor,y_train_mayor) #fiteamos el modelo
predictions_mayor = clf_mayor.predict(X_test_mayor) #Generamos las predicciones
predictions_mayor_s=pd.DataFrame(predictions_mayor).reset_index()
mayor_2 =  pd.concat([X_test_mayor.reset_index(), predictions_mayor_s], axis=1)
confusion_matrix(y_test_mayor, predictions_mayor)

array([[325, 219],
       [210, 148]])

### 6.2 Agregar resultados a dataframe de muestreo




En la base de datos que se construirá, se dejarán los valores de la matriz de confusión de cada uno de los segmentos con el modelo dummy.

In [65]:
# initialize list of lists
data = [['menor',279, 239,208,198], ['joven', 341, 244, 238, 182], ['adulto', 29,41,35,46],['mayor',325,219,210,148]]
  
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['segmento', 'TP', 'FP','FN','TN'])
  
# print dataframe.
df

segmento   TP   FP   FN   TN
0    menor  279  239  208  198
1    joven  341  244  238  182
2   adulto   29   41   35   46
3    mayor  325  219  210  148

### 6.3 Visualizar según rangos etarios

#### Menor

In [128]:
fig = px.scatter(menor_2, x='comp1', y='comp2', color=0)
fig.show()

####Joven

In [132]:
fig = px.scatter(joven_2, x='comp1', y='comp2', color=0)
fig.show()

####Adulto

In [133]:
fig = px.scatter(adulto_2, x='comp1', y='comp2', color=0)
fig.show()

####Mayor

In [134]:
fig = px.scatter(mayor_2, x='comp1', y='comp2', color=0)
fig.show()

### 6.4 Calcular ratios y responder

In [ ]:
...